#!/bin/bash

# WYX CLI - Shell Functions Generator
# This script generates shell functions for all wyx commands
# so they can be used directly without the 'wyx' prefix

WYX_DIR="$(dirname "$0")"
CSV_FILE="$WYX_DIR/src/data/arg_scripts.csv"
OUTPUT_FILE="$WYX_DIR/wyx-functions.sh"

echo "# WYX CLI Auto-generated Functions" > "$OUTPUT_FILE"
echo "# Generated on $(date)" >> "$OUTPUT_FILE"
echo "# DO NOT EDIT THIS FILE MANUALLY" >> "$OUTPUT_FILE"
echo "# Regenerate by running: $WYX_DIR/generate-shell-functions.sh" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Read all public commands from CSV (skip header, only get public commands)
while IFS=',' read -r id path name public args category_id; do
    # Skip header
    if [ "$id" = "id" ]; then
        continue
    fi
    
    # Only process public commands (public=true)
    if [ "$public" = "true" ]; then
        # Skip commands that might conflict with common shell commands
        # We'll handle 'cd' specially since wyx has its own cd
        if [ "$id" = "cd" ]; then
            echo "# Note: 'cd' is handled by wyx cd for directory aliases" >> "$OUTPUT_FILE"
            echo "wyxcd() { wyx cd \"\$@\"; }" >> "$OUTPUT_FILE"
            echo "" >> "$OUTPUT_FILE"
            continue
        fi
        
        # Generate function for each command
        echo "${id}() { wyx ${id} \"\$@\"; }" >> "$OUTPUT_FILE"
    fi
done < "$CSV_FILE"

echo "" >> "$OUTPUT_FILE"
echo "# End of WYX CLI Auto-generated Functions" >> "$OUTPUT_FILE"

echo "✓ Generated shell functions in: $OUTPUT_FILE"
echo ""
echo "To use these functions, add this line to your ~/.zshrc:"
echo "source $OUTPUT_FILE"
