# Toolbox Auto-generated Functions
# Generated on Fri Mar 27 14:15:21 CET 2026
# DO NOT EDIT THIS FILE MANUALLY
# Regenerate by running: /Users/pwt9708/SpringerNature/Scripts/toolbox/generate-shell-functions.sh

sys-info() { tool sys-info "$@"; }
# Note: 'cd' is handled by tool cd for directory aliases
toolcd() { tool cd "$@"; }

back() { tool back "$@"; }
run() { tool run "$@"; }
vsc() { tool vsc "$@"; }
genpass() { tool genpass "$@"; }
genhex() { tool genhex "$@"; }
genb64() { tool genb64 "$@"; }
version() { tool version "$@"; }
ginit() { tool ginit "$@"; }
push() { tool push "$@"; }
pull() { tool pull "$@"; }
mpull() { tool mpull "$@"; }
repo() { tool repo "$@"; }
branch() { tool branch "$@"; }
pipelines() { tool pipelines "$@"; }
issues() { tool issues "$@"; }
prs() { tool prs "$@"; }
notifs() { tool notifs "$@"; }
commits() { tool commits "$@"; }
lastcommit() { tool lastcommit "$@"; }
nb() { tool nb "$@"; }
pr() { tool pr "$@"; }
bpr() { tool bpr "$@"; }
profile() { tool profile "$@"; }
org() { tool org "$@"; }
# help() conflicts with system alias - use 'tool help' directly
user() { tool user "$@"; }
mydirs() { tool mydirs "$@"; }
myorgs() { tool myorgs "$@"; }
myscripts() { tool myscripts "$@"; }
todo() { tool todo "$@"; }
editd() { tool editd "$@"; }
edits() { tool edits "$@"; }
newscript() { tool newscript "$@"; }
find() { tool find "$@"; }
delete() { tool delete "$@"; }
lastcmd() { tool lastcmd "$@"; }
ip() { tool ip "$@"; }
wifi() { tool wifi "$@"; }
hardware-ports() { tool hardware-ports "$@"; }
wpass() { tool wpass "$@"; }
speedtest() { tool speedtest "$@"; }
genqr() { tool genqr "$@"; }
upscale() { tool upscale "$@"; }
fopen() { tool fopen "$@"; }
encrypt() { tool encrypt "$@"; }
decrypt() { tool decrypt "$@"; }
weather() { tool weather "$@"; }
moon() { tool moon "$@"; }
leap-year() { tool leap-year "$@"; }
webtext() { tool webtext "$@"; }
explain() { tool explain "$@"; }
ask-opencode() { tool ask-opencode "$@"; }
google() { tool google "$@"; }
install-deps() { tool install-deps "$@"; }
keystore() { tool keystore "$@"; }
copy() { tool copy "$@"; }
update-deps() { tool update-deps "$@"; }
list-deps() { tool list-deps "$@"; }
pp() { tool pp "$@"; }
port-scan() { tool port-scan "$@"; }
multiplex() { tool multiplex "$@"; }
quote() { tool quote "$@"; }
today() { tool today "$@"; }
deploy() { tool deploy "$@"; }
nemo-test() { source /Users/pwt9708/SpringerNature/Scripts/toolbox/src/commands/nemo-test.sh "$@"; }
test-boot()    { ~/.sn-zsh-personal/scripts/test-boot.sh "$@"; }
backup-boot()  { ~/.sn-zsh-personal/scripts/backup-boot.sh "$@"; }
lock-boot()    { ~/.sn-zsh-personal/scripts/lock-boot.sh "$@"; }
unlock-boot()  { ~/.sn-zsh-personal/scripts/unlock-boot.sh "$@"; }

# End of Toolbox Auto-generated Functions
