# WYX CLI Auto-generated Functions
# Generated on Tue May 12 18:49:03 CEST 2026
# DO NOT EDIT THIS FILE MANUALLY
# Regenerate by running: /Users/pwt9708/SpringerNature/Scripts/toolbox/generate-shell-functions.sh

sys-info() { wyx sys-info "$@"; }
# Note: 'cd' is handled by wyx cd for directory aliases
wyxcd() { wyx cd "$@"; }

back() { wyx back "$@"; }
run() { wyx run "$@"; }
vsc() { wyx vsc "$@"; }
genpass() { wyx genpass "$@"; }
genhex() { wyx genhex "$@"; }
genb64() { wyx genb64 "$@"; }
version() { wyx version "$@"; }
ginit() { wyx ginit "$@"; }
push() { wyx push "$@"; }
pull() { wyx pull "$@"; }
mpull() { wyx mpull "$@"; }
repo() { wyx repo "$@"; }
branch() { wyx branch "$@"; }
pipelines() { wyx pipelines "$@"; }
issues() { wyx issues "$@"; }
prs() { wyx prs "$@"; }
notifs() { wyx notifs "$@"; }
commits() { wyx commits "$@"; }
lastcommit() { wyx lastcommit "$@"; }
nb() { wyx nb "$@"; }
pr() { wyx pr "$@"; }
bpr() { wyx bpr "$@"; }
profile() { wyx profile "$@"; }
org() { wyx org "$@"; }
help() { wyx help "$@"; }
user() { wyx user "$@"; }
mydirs() { wyx mydirs "$@"; }
myorgs() { wyx myorgs "$@"; }
myscripts() { wyx myscripts "$@"; }
todo() { wyx todo "$@"; }
editd() { wyx editd "$@"; }
edits() { wyx edits "$@"; }
newscript() { wyx newscript "$@"; }
find() { wyx find "$@"; }
delete() { wyx delete "$@"; }
lastcmd() { wyx lastcmd "$@"; }
ip() { wyx ip "$@"; }
wifi() { wyx wifi "$@"; }
hardware-ports() { wyx hardware-ports "$@"; }
wpass() { wyx wpass "$@"; }
speedtest() { wyx speedtest "$@"; }
genqr() { wyx genqr "$@"; }
upscale() { wyx upscale "$@"; }
fopen() { wyx fopen "$@"; }
encrypt() { wyx encrypt "$@"; }
decrypt() { wyx decrypt "$@"; }
weather() { wyx weather "$@"; }
moon() { wyx moon "$@"; }
leap-year() { wyx leap-year "$@"; }
webtext() { wyx webtext "$@"; }
explain() { wyx explain "$@"; }
ask-opencode() { wyx ask-opencode "$@"; }
google() { wyx google "$@"; }
install-deps() { wyx install-deps "$@"; }
keystore() { wyx keystore "$@"; }
copy() { wyx copy "$@"; }
update-deps() { wyx update-deps "$@"; }
list-deps() { wyx list-deps "$@"; }
pp() { wyx pp "$@"; }
port-scan() { wyx port-scan "$@"; }
multiplex() { wyx multiplex "$@"; }
quote() { wyx quote "$@"; }
today() { wyx today "$@"; }
deploy() { wyx deploy "$@"; }
nemo-test() { wyx nemo-test "$@"; }

# End of WYX CLI Auto-generated Functions
